name: Wish Pool CI

on:
  create:
    tags: v*
  # push:
  #   branches: [ main, dev ]

jobs:
  build:
    name: Build Appbundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.2'
    - name: Decode base64 firebase_options
      run: echo $FIREBASE_OPTIONS | base64 -di > lib/firebase_options.dart
      env:
        FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
    - name: Decode base64 upload_keystore
      run: echo $UPLOAD_KEYSTORE | base64 -di > android/app/upload-keystore.jks
      env:
        UPLOAD_KEYSTORE: ${{ secrets.UPLOAD_KEYSTORE }}
    - name: Decode base64 signing_key
      run: echo $SIGNING_KEY | base64 -di > android/key.properties
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    - name: Decode base64 google_services
      run: echo $GOOGLE_SERVICES | base64 -di > android/app/google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build appbundle
    - name: Create release bundle
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/pooja/Documents/Study/apps/wish_pool_app/wish_pool/build/app/outputs/bundle/release/*.aab"
        token: ${{  secrets.TOKEN  }}